#include <SPIRV_Cross/spirv_cfg.cpp>
#include <SPIRV_Cross/spirv_cpp.cpp>
#include <SPIRV_Cross/spirv_cross.cpp>
#include <SPIRV_Cross/spirv_cross_parsed_ir.cpp>
#include <SPIRV_Cross/spirv_cross_util.cpp>
#include <SPIRV_Cross/spirv_glsl.cpp>
#include <SPIRV_Cross/spirv_hlsl.cpp>
#include <SPIRV_Cross/spirv_msl.cpp>
#include <SPIRV_Cross/spirv_parser.cpp>
#include <SPIRV_Cross/spirv_reflect.cpp>